version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - chmod +x gradlew
      - echo Build started on `date`
      - ./gradlew bootWar
artifacts:
  files:
    - build/libs/hms-v3-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*
  base-directory: 'build/libs'
  discard-paths: yes